"""Reading a phpBB post body.

A survey of thirty captured posts found fourteen distinct tags, all generated by
phpBB's own templates, so the standard library's HTML parser is enough and
Sextile keeps a single runtime dependency.

Three details are specific to phpBB and worth naming:

- Every body ends with a `Statistics: Posted by ...` paragraph and a rule. It is
  plumbing, and it is stripped -- but only after `feed.atom` has mined it for
  the author's numeric id, which appears nowhere else.
- A quotation arrives as `<blockquote class="uncited"><div>`, and quotations
  nest.
- A code listing arrives as `<div class="codebox"><p>Code: </p><pre><code>`,
  where the `Code: ` label is furniture rather than content.
"""

from __future__ import annotations

import re
from html.parser import HTMLParser
from typing import Final

from sextile.content.blocks import (
    Attachment,
    Block,
    Code,
    Image,
    Link,
    ListItem,
    Paragraph,
    PostContent,
    Quote,
)

_FOOTER_MARKER: Final = "Statistics: Posted by"

#  Tags that end the current line without ending the paragraph.
_LINE_BREAK: Final = "br"

#  Tags after which running text should start a new paragraph.
_PARAGRAPH_TAGS: Final = frozenset({"p", "div", "dl", "dt", "dd", "hr", "ul", "ol", "table", "tr"})

_WHITESPACE: Final = re.compile(r"\s+")


def parse_post_body(body: str) -> PostContent:
    """Parse a phpBB post body into blocks."""
    parser = _BodyParser()
    parser.feed(_without_footer(body))
    parser.close()
    return PostContent(blocks=tuple(parser.blocks), links=tuple(parser.links))


def _without_footer(body: str) -> str:
    """Drop phpBB's trailing statistics paragraph and rule."""
    marker = body.find(_FOOTER_MARKER)
    if marker == -1:
        return body
    #  Cut at the paragraph that opens the footer, not at the marker itself.
    opening = body.rfind("<p", 0, marker)
    return body[: opening if opening != -1 else marker]


class _BodyParser(HTMLParser):
    """Accumulates blocks while walking the markup.

    Quotations nest, so blocks accumulate onto a stack: entering a blockquote
    pushes a fresh list, leaving it pops that list into a Quote.
    """

    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self._stack: list[list[Block]] = [[]]
        self._lines: list[str] = []
        self._words: list[str] = []
        self.links: list[Link] = []
        self._open_links: list[int | None] = []
        self._code: list[str] | None = None
        self._in_code_label = False
        self._suppress_depth = 0

    @property
    def blocks(self) -> list[Block]:
        self._end_paragraph()
        return self._stack[0]

    # -- elements -----------------------------------------------------------

    def handle_starttag(self, tag: str, attributes: list[tuple[str, str | None]]) -> None:
        values = {name: value or "" for name, value in attributes}
        classes = values.get("class", "").split()

        if tag == "img":
            self._image(values, classes)
            return
        if tag == "a":
            self._link_start(values)
            return
        if tag == "blockquote":
            self._end_paragraph()
            self._stack.append([])
            return
        if tag == "pre":
            self._end_paragraph()
            self._code = []
            return
        if tag == "p" and self._code is None and "codebox" in self._parent_classes:
            #  The "Code: " label above a listing is furniture.
            self._in_code_label = True
            return
        if tag == _LINE_BREAK:
            self._end_line()
            return
        if tag in _PARAGRAPH_TAGS:
            self._end_paragraph()
        if tag == "div":
            self._parent_classes = classes

    def handle_endtag(self, tag: str) -> None:
        if tag == "a":
            self._link_end()
            return
        if tag == "blockquote":
            self._end_paragraph()
            inner = self._stack.pop()
            if inner:
                self._stack[-1].append(Quote(tuple(inner)))
            return
        if tag == "pre":
            if self._code:
                self._emit(Code(tuple(self._code)))
            self._code = None
            return
        if tag == "p" and self._in_code_label:
            self._in_code_label = False
            return
        if tag == "li":
            text = self._flush_text()
            if text:
                self._emit(ListItem(text))
            return
        if tag == "dt":
            self._attachment()
            return
        if tag in _PARAGRAPH_TAGS:
            self._end_paragraph()

    def handle_data(self, data: str) -> None:
        if self._in_code_label or self._suppress_depth:
            return
        if self._code is not None:
            self._code.extend(data.splitlines() or [data])
            return
        stripped = _WHITESPACE.sub(" ", data)
        if stripped.strip():
            self._words.append(stripped)

    # -- pieces -------------------------------------------------------------

    _parent_classes: list[str] = []

    def _image(self, values: dict[str, str], classes: list[str]) -> None:
        if "smilies" in classes:
            #  The alt attribute holds what the poster actually typed, which is
            #  shorter and more honest than describing the picture.
            self._words.append(values.get("alt", ""))
            return
        self._end_paragraph()
        self._emit(Image(values.get("alt", "")))

    def _link_start(self, values: dict[str, str]) -> None:
        url = values.get("href", "")
        self._open_links.append(None if _uninteresting(url) else self._reference(url))

    def _link_end(self) -> None:
        """Place the reference after the anchor's own text, as `this page [1]`."""
        if not self._open_links:
            return
        number = self._open_links.pop()
        if number is not None:
            self._words.append(f" [{number}]")

    def _reference(self, url: str) -> int:
        for link in self.links:
            if link.url == url:
                return link.number
        number = len(self.links) + 1
        self.links.append(Link(number=number, text="", url=url))
        return number

    def _attachment(self) -> None:
        text = self._flush_text()
        if text:
            self._emit(Attachment(text))

    # -- text ---------------------------------------------------------------

    def _end_line(self) -> None:
        text = self._flush_text()
        if text:
            self._lines.append(text)
        elif self._lines:
            #  A second break in a row ends the paragraph.
            self._end_paragraph()

    def _end_paragraph(self) -> None:
        text = self._flush_text()
        if text:
            self._lines.append(text)
        if self._lines:
            self._stack[-1].append(Paragraph(tuple(self._lines)))
            self._lines = []

    def _flush_text(self) -> str:
        joined = "".join(self._words)
        self._words = []
        return _WHITESPACE.sub(" ", joined).strip()

    def _emit(self, block: Block) -> None:
        self._end_paragraph()
        self._stack[-1].append(block)


def _uninteresting(url: str) -> bool:
    """Whether a link is plumbing rather than somewhere a reader wanted to go.

    The footer's author link is phpBB's own furniture. Attachment downloads are
    named by an Attachment block instead, are forbidden to us by robots.txt, and
    could not be fetched on a BBC Micro in any case.
    """
    return not url or "memberlist.php" in url or "download/file.php" in url
